version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: mysql:latest
        environment:
          - MYSQL_ROOT_PASSWORD=root123
          - MYSQL_DATABASE=spring_app_db
          - MYSQL_USER=app_user
          - MYSQL_PASSWORD=test123
        ports:
          - "2012:3306"
        volumes:
          - /data/mysql

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/circleci-scrumban

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./server/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      #      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "./server/pom.xml" }}

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: ./server/target/surefire-reports

      # run tests!
      - run: cd ./server && mvn clean install
