version: 2

aliases:
  - &defaults
    working_directory: ~/circleci-scrumban
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  build:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: mysql:latest
        environment:
          - MYSQL_ROOT_PASSWORD=root123
          - MYSQL_DATABASE=spring_app_db
          - MYSQL_USER=app_user
          - MYSQL_PASSWORD=test123
        ports:
          - "2012:3306"
        volumes:
          - /data/mysql

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout

  test:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      #   # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./server/pom.xml" }}
            - v1-dependencies-
      - run: cd ./server && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "./server/pom.xml" }}
      # run tests!
      - run:
          name: clean install
          command: cd ./server && mvn clean install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
