version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123

    ports:
      - "2012:3306"

    volumes:
      - /data/mysql

#  scrumban-jpa-app:
#    image: scrumban-image
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql-docker-container
#
#    ports:
#      - 8070:8080
#    volumes:
#      - /data/scrumban-app